#配置项目启动端口号
server:
  port: 8080
#配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mybatis_demo1?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
  devtools:
    add-properties: true
    restart:
      additional-paths: src/main/java
#配置Mybatis和xml映射
mybatis:
  # sql映射文件地址
  mapper-locations: classpath:mapper/*.xml
  #别名
  type-aliases-package: cn.lyj.entity

# 配置日志级别
logging:
  level:
    cn.lyj.mapper: debug

# 配置Swagger
springdoc:
  swagger-ui.path: /swagger-ui.html




